spring.application.name=demo
server.port=8081
server.servlet.context-path=/SCMTest

management.endpoints.web.basepath=/
# management.endpoints.web.exposure.include=health
# management.endpoint.health.show-details=always
# management.endpoint.health.probes.enabled=true


# springdoc.paths-to-exclude=/actuator/**,/error

management.server.port=8081
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=true
management.health.readinessstate.enabled=true