spring.application.name=demo
server.port=8080
server.servlet.context-path=/hola/ailen/como/esta/ola/k/ase/desde/mi/context/path/de/prueba/uwu

management.endpoints.web.basepath=/
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=true


